feat: :white_check_mark: add client module
agencia-de-viajes-cincinnatus/BACKEND pull request #7
Opened 2023-12-03 02:29 UTC by MaikJim

2023-12-04 14:04 UTC, dearson33 commented
No description provided.

2023-12-04 14:24 UTC, enmanuelsabarua requested changes
Hay algunos aspectos que se deben cambiar para que el codigo no difiera tanto del que ya se ha creado.

2023-12-04 14:24 UTC, enmanuelsabarua commented on src/client/client.controller.ts
> +  findOne(@Param('id') id: string) {
Para `(@Param('id')` puedes usar `(@Param('id', ParseUUIDPipe)` para asegurar que el id se pase en el formato correcto sin tener que pasarlo a int con `+id`

2023-12-04 14:24 UTC, enmanuelsabarua commented on src/client/client.service.ts
> +  findOne(id: number) {
Los IDs en este caso seran de tipo `id: string` porque para mas seguridad vamos a usar UUID.

2023-12-04 14:24 UTC, enmanuelsabarua commented on src/client/entities/client.entity.ts
Recuerda que las entitades las vamos a declarar en `src/typeorm/entities` para mas organizacion.

2023-12-04 20:13 UTC, MaikJim commented
No te entiendo @dearson33 podrías ser más descriptivo por favor

2023-12-04 20:14 UTC, MaikJim commented
Está bien @enmanuelsabarua agregaré esos cambios, Gracias

2023-12-05 02:56 UTC, dearson33 commented
> No te entiendo @dearson33 podrías ser más descriptivo por favor

osea eso que le farta la descripcion al PR jeje y ese es el mensaje que tiene "No description provided."

2023-12-07 16:51 UTC, MaikJim commented
Ya, agregue los cambios, verifíquenlos por favor y cualquier cosa me avisan si debo cambiar algo más.

2023-12-07 17:14 UTC, enmanuelsabarua commented
@MaikJim los nuevos cambios no se agregaron a este PR, abre un PR nuevo con los cambios

2023-12-07 17:33 UTC, closed without merging